### ISSUE TITLE
getting this started 

### ISSUE THREAD

**Issue by SuperDuperOne** [jbfavre/dashing-googleanalyticsrt#1]
Hi @jbfavre 

I've download smashing and have the template one running just fine (https://smashing.github.io/)
however reading your notes I'm not sure i follow along (newbie)
I understand this fairly old, but this is exactly what I'm looking for.

I'm looking to get Google Analytics displaying real time visitors into the widgets.  

hope you can help.

thanks

**Comment by SuperDuperOne** [comment]
I also noticed that there is no data getting pulled in even though I've given the service account role VIEWER and ADMIN. 
Any help would be appreciated @jbfavre thanks again

**Comment by SuperDuperOne** [comment]
orrie@macbookpro:/Users/alan/sandbox/dashing_dashboard/webdev_dash/widgets/visitor_count $ smashing start
bundler: failed to load command: thin (/usr/local/bin/thin)
Errno::ENOENT: No such file or directory @ rb_sysopen - config.ru
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `read'
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `load'
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:22:in `load'
  /usr/local/bin/thin:22:in `<top (required)>'

**Comment by jbfavre** [comment]
Hello,
I'm sorry, but I stopped using dashing years ago.
The code here hasn't change for years now, it's likely both dashing & GA APIs have changed.
I'm afraid I won't be able to help you

**Comment by SuperDuperOne** [comment]
Hi @jbfavre 
Thanks for getting back to me, do you know of any other alternative to Dashing that I could to get the same result you described here?
